# Generated by Django 5.2.13 on 2026-04-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('operations', '0002_enforce_task005_audit_guards'),
        ('stores', '0002_businessgroup_comments_businessgroup_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(db_index=True, max_length=16)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=32)),
                ('last_values', models.JSONField(blank=True, default=dict)),
                ('first_detected_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stores.storeaccount')),
            ],
            options={
                'ordering': ['marketplace', 'store__name', 'sku', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('change_type', models.CharField(choices=[('detected', 'Detected'), ('updated', 'Updated')], max_length=32)),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_history', to='files.fileversion')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_history', to='operations.operation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='marketplace_products.marketplaceproduct')),
            ],
            options={
                'ordering': ['-detected_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplaceproduct',
            index=models.Index(fields=['marketplace', 'store', 'status'], name='marketplace_marketp_66d9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceproduct',
            index=models.Index(fields=['last_seen_at'], name='marketplace_last_se_77204a_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceproduct',
            constraint=models.UniqueConstraint(fields=('marketplace', 'store', 'sku'), name='uniq_marketplace_product_store_sku'),
        ),
        migrations.AddIndex(
            model_name='marketplaceproducthistory',
            index=models.Index(fields=['product', 'detected_at'], name='marketplace_product_311f78_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplaceproducthistory',
            index=models.Index(fields=['operation', 'detected_at'], name='marketplace_operati_d24caa_idx'),
        ),
    ]
