# Generated by Django 5.2.13 on 2026-04-25 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_access', '0002_seed_identity_access'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaccess',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_access', to='stores.storeaccount'),
        ),
        migrations.AlterField(
            model_name='storeaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userblockhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='block_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userchangehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_overrides', to='stores.storeaccount'),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersectionaccessoverride',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='section_overrides', to='stores.storeaccount'),
        ),
        migrations.AlterField(
            model_name='usersectionaccessoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_overrides', to=settings.AUTH_USER_MODEL),
        ),
    ]
