# Generated by Django 5.2.13 on 2026-04-26 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0002_remove_fileobject_file_object_scenario_marketplace_match_and_more'),
        ('operations', '0004_allow_multiple_operation_outputs_per_kind'),
        ('stores', '0003_connectionblock_is_stage2_1_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_promotion_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('is_current_at_fetch', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wb_promotions', to='stores.storeaccount')),
            ],
            options={
                'ordering': ['-last_seen_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WBPromotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField()),
                ('api_window_start', models.DateTimeField()),
                ('api_window_end', models.DateTimeField()),
                ('current_filter_timestamp', models.DateTimeField()),
                ('raw_response_safe_snapshot', models.JSONField(blank=True, default=dict)),
                ('promotions_count', models.PositiveIntegerField(default=0)),
                ('current_promotions_count', models.PositiveIntegerField(default=0)),
                ('regular_current_promotions_count', models.PositiveIntegerField(default=0)),
                ('auto_current_promotions_count', models.PositiveIntegerField(default=0)),
                ('promotion_products_count', models.PositiveIntegerField(default=0)),
                ('invalid_product_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wb_promotion_snapshot', to='operations.operation')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wb_promotion_snapshots', to='stores.storeaccount')),
            ],
            options={
                'ordering': ['-fetched_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WBPromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmID', models.CharField(max_length=64)),
                ('inAction', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currencyCode', models.CharField(blank=True, max_length=16)),
                ('planPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discount', models.JSONField(blank=True, null=True)),
                ('planDiscount', models.JSONField(blank=True, null=True)),
                ('row_status', models.CharField(max_length=32)),
                ('reason_code', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='promotions.wbpromotion')),
                ('source_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='promotions.wbpromotionsnapshot')),
            ],
            options={
                'ordering': ['promotion_id', 'nmID', 'inAction', 'id'],
            },
        ),
        migrations.AddField(
            model_name='wbpromotion',
            name='snapshot_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='promotions.wbpromotionsnapshot'),
        ),
        migrations.CreateModel(
            name='WBPromotionExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wb_promotion_export_file', to='files.fileversion')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wb_promotion_export_files', to='operations.operation')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='export_files', to='promotions.wbpromotion')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['promotion', 'operation'], name='promotions__promoti_059aae_idx')],
                'constraints': [models.UniqueConstraint(fields=('promotion', 'operation', 'file_version'), name='uniq_wb_promotion_export_file_link')],
            },
        ),
        migrations.AddIndex(
            model_name='wbpromotionsnapshot',
            index=models.Index(fields=['store', 'fetched_at'], name='promotions__store_i_0ca364_idx'),
        ),
        migrations.AddIndex(
            model_name='wbpromotionsnapshot',
            index=models.Index(fields=['operation'], name='promotions__operati_9c46ca_idx'),
        ),
        migrations.AddIndex(
            model_name='wbpromotionproduct',
            index=models.Index(fields=['promotion', 'nmID'], name='promotions__promoti_5ad43d_idx'),
        ),
        migrations.AddIndex(
            model_name='wbpromotionproduct',
            index=models.Index(fields=['source_snapshot', 'row_status'], name='promotions__source__dd1e69_idx'),
        ),
        migrations.AddIndex(
            model_name='wbpromotionproduct',
            index=models.Index(fields=['reason_code'], name='promotions__reason__7cf6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='wbpromotion',
            index=models.Index(fields=['store', 'wb_promotion_id'], name='promotions__store_i_2afe40_idx'),
        ),
        migrations.AddIndex(
            model_name='wbpromotion',
            index=models.Index(fields=['store', 'is_current_at_fetch'], name='promotions__store_i_bc849f_idx'),
        ),
        migrations.AddIndex(
            model_name='wbpromotion',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='promotions__start_d_3fbdd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='wbpromotion',
            constraint=models.UniqueConstraint(fields=('store', 'wb_promotion_id'), name='uniq_wb_promotion_store_api_id'),
        ),
    ]
