# Generated by Django 5.2.13 on 2026-04-25 16:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('platform_settings', '0002_seed_wb_system_parameters'),
        ('stores', '0002_businessgroup_comments_businessgroup_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreParameterChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(max_length=128)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('old_source', models.CharField(blank=True, max_length=16)),
                ('new_source', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='storeparametervalue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storeparametervalue',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='storeparametervalue',
            index=models.Index(fields=['store', 'parameter_code', 'is_active'], name='platform_se_store_i_c5d76d_idx'),
        ),
        migrations.AddField(
            model_name='storeparameterchangehistory',
            name='audit_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parameter_history_records', to='audit.auditrecord'),
        ),
        migrations.AddField(
            model_name='storeparameterchangehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_parameter_history_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeparameterchangehistory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameter_history', to='stores.storeaccount'),
        ),
        migrations.AddIndex(
            model_name='storeparameterchangehistory',
            index=models.Index(fields=['store', 'parameter_code', 'changed_at'], name='platform_se_store_i_6235c2_idx'),
        ),
    ]
