# Generated by Django 5.2.13 on 2026-05-01 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0010_remove_operation_ozon_api_operation_has_step_and_non_check_type_and_more'),
        ('stores', '0003_connectionblock_is_stage2_1_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'WB'), ('ozon', 'Ozon')], max_length=16)),
                ('sync_type', models.CharField(choices=[('listings', 'Listings'), ('prices', 'Prices'), ('stocks', 'Stocks'), ('sales', 'Sales'), ('orders', 'Orders'), ('promotions', 'Promotions'), ('full_catalog_refresh', 'Full catalog refresh'), ('mapping_import', 'Mapping import')], max_length=64)),
                ('source', models.CharField(choices=[('excel', 'Excel'), ('wb_api_prices', 'WB API prices'), ('ozon_api_actions', 'Ozon API actions'), ('manual_import', 'Manual import'), ('migration', 'Migration'), ('future', 'Future')], max_length=64)),
                ('launch_method', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('service', 'Service'), ('api', 'API')], default='manual', max_length=16)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed_success', 'Completed successfully'), ('completed_with_warnings', 'Completed with warnings'), ('completed_with_error', 'Completed with error'), ('interrupted_failed', 'Interrupted / failed')], default='created', max_length=32)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_sync_runs', to='operations.operation')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_marketplace_sync_runs', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_sync_runs', to='stores.storeaccount')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('wb', 'WB'), ('ozon', 'Ozon')], max_length=16)),
                ('external_primary_id', models.CharField(max_length=255)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('seller_article', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('category_external_id', models.CharField(blank=True, max_length=255)),
                ('listing_status', models.CharField(choices=[('active', 'Active'), ('not_seen_last_sync', 'Not seen in last sync'), ('inactive', 'Inactive'), ('archived', 'Archived'), ('sync_error', 'Sync error')], default='active', max_length=32)),
                ('mapping_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('needs_review', 'Needs review'), ('conflict', 'Conflict'), ('archived', 'Archived')], default='unmatched', max_length=32)),
                ('last_values', models.JSONField(blank=True, default=dict)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_source', models.CharField(choices=[('excel', 'Excel'), ('wb_api_prices', 'WB API prices'), ('ozon_api_actions', 'Ozon API actions'), ('manual_import', 'Manual import'), ('migration', 'Migration'), ('future', 'Future')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_listings', to='stores.storeaccount')),
                ('last_sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='latest_listings', to='product_core.marketplacesyncrun')),
            ],
            options={
                'ordering': ['marketplace', 'store__name', 'external_primary_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ListingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('appeared', 'Appeared'), ('updated', 'Updated'), ('status_changed', 'Status changed')], max_length=32)),
                ('changed_at', models.DateTimeField()),
                ('changed_fields', models.JSONField(blank=True, default=list)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(choices=[('excel', 'Excel'), ('wb_api_prices', 'WB API prices'), ('ozon_api_actions', 'Ozon API actions'), ('manual_import', 'Manual import'), ('migration', 'Migration'), ('future', 'Future')], max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_history_changes', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_history', to='operations.operation')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='product_core.marketplacelisting')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_history', to='product_core.marketplacesyncrun')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_with_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(max_length=16)),
                ('raw_safe', models.JSONField(blank=True, default=dict)),
                ('source_endpoint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_snapshots', to='product_core.marketplacelisting')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_snapshots', to='operations.operation')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_snapshots', to='product_core.marketplacesyncrun')),
            ],
            options={
                'ordering': ['-snapshot_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=32)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='product_core.productcategory')),
            ],
            options={
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InternalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('finished_good', 'Finished good'), ('material', 'Material'), ('packaging', 'Packaging'), ('semi_finished', 'Semi-finished'), ('kit', 'Kit'), ('service_or_design_artifact', 'Service or design artifact'), ('unknown', 'Unknown')], default='unknown', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=32)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_internal_products', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_internal_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_core.productcategory')),
            ],
            options={
                'ordering': ['internal_code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_sku', models.CharField(blank=True, max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('barcode_internal', models.CharField(blank=True, max_length=128)),
                ('variant_attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='product_core.internalproduct')),
            ],
            options={
                'ordering': ['product__internal_code', 'internal_sku', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductMappingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('map', 'Map'), ('unmap', 'Unmap'), ('conflict_marker', 'Conflict marker'), ('needs_review_marker', 'Needs review marker')], max_length=32)),
                ('mapping_status_after', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('needs_review', 'Needs review'), ('conflict', 'Conflict'), ('archived', 'Archived')], max_length=32)),
                ('changed_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('excel', 'Excel'), ('wb_api_prices', 'WB API prices'), ('ozon_api_actions', 'Ozon API actions'), ('manual_import', 'Manual import'), ('migration', 'Migration'), ('future', 'Future')], max_length=64)),
                ('source_context', models.JSONField(blank=True, default=dict)),
                ('reason_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_mapping_history', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_history', to='product_core.marketplacelisting')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_mapping_history', to='operations.operation')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mapping_history', to='product_core.marketplacesyncrun')),
                ('new_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_mapping_history', to='product_core.productvariant')),
                ('previous_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_mapping_history', to='product_core.productvariant')),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(choices=[('internal_sku', 'Internal SKU'), ('internal_barcode', 'Internal barcode'), ('supplier_sku', 'Supplier SKU'), ('wb_vendor_code', 'WB vendor code'), ('ozon_offer_id', 'Ozon offer ID'), ('legacy_article', 'Legacy article')], max_length=64)),
                ('value', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('migration', 'Migration'), ('import', 'Import'), ('api', 'API'), ('future', 'Future')], default='manual', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identifiers', to='product_core.productvariant')),
            ],
            options={
                'ordering': ['variant_id', 'identifier_type', 'source', 'value', 'id'],
            },
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='internal_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_listings', to='product_core.productvariant'),
        ),
        migrations.CreateModel(
            name='PromotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_promotion_id', models.CharField(max_length=255)),
                ('action_name', models.CharField(blank=True, max_length=255)),
                ('participation_status', models.CharField(max_length=64)),
                ('action_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('constraints', models.JSONField(blank=True, default=dict)),
                ('reason_code', models.CharField(blank=True, max_length=128)),
                ('raw_safe', models.JSONField(blank=True, default=dict)),
                ('source_endpoint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_snapshots', to='product_core.marketplacelisting')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotion_snapshots', to='operations.operation')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_snapshots', to='product_core.marketplacesyncrun')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesPeriodSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('orders_qty', models.IntegerField(blank=True, null=True)),
                ('sales_qty', models.IntegerField(blank=True, null=True)),
                ('buyout_qty', models.IntegerField(blank=True, null=True)),
                ('returns_qty', models.IntegerField(blank=True, null=True)),
                ('sales_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=16)),
                ('raw_safe', models.JSONField(blank=True, default=dict)),
                ('source_endpoint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_period_snapshots', to='product_core.marketplacelisting')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_period_snapshots', to='operations.operation')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_period_snapshots', to='product_core.marketplacesyncrun')),
            ],
            options={
                'ordering': ['-period_start', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_at', models.DateTimeField()),
                ('total_stock', models.IntegerField(blank=True, null=True)),
                ('stock_by_warehouse', models.JSONField(blank=True, default=dict)),
                ('in_way_to_client', models.IntegerField(blank=True, null=True)),
                ('in_way_from_client', models.IntegerField(blank=True, null=True)),
                ('raw_safe', models.JSONField(blank=True, default=dict)),
                ('source_endpoint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='product_core.marketplacelisting')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='operations.operation')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_snapshots', to='product_core.marketplacesyncrun')),
            ],
            options={
                'ordering': ['-snapshot_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='marketplacesyncrun',
            index=models.Index(fields=['marketplace', 'store', 'sync_type', 'status'], name='product_cor_marketp_5e8b6e_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacesyncrun',
            index=models.Index(fields=['source', 'started_at'], name='product_cor_source_f05f75_idx'),
        ),
        migrations.AddIndex(
            model_name='listinghistory',
            index=models.Index(fields=['listing', 'changed_at'], name='product_cor_listing_18d83d_idx'),
        ),
        migrations.AddIndex(
            model_name='listinghistory',
            index=models.Index(fields=['sync_run', 'changed_at'], name='product_cor_sync_ru_e07086_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['listing', 'snapshot_at'], name='product_cor_listing_17a004_idx'),
        ),
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['sync_run', 'snapshot_at'], name='product_cor_sync_ru_6fbfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent', 'status', 'sort_order'], name='product_cor_parent__6aa07f_idx'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='uniq_product_category_parent_name'),
        ),
        migrations.AddIndex(
            model_name='internalproduct',
            index=models.Index(fields=['status'], name='product_cor_status_58ffc9_idx'),
        ),
        migrations.AddIndex(
            model_name='internalproduct',
            index=models.Index(fields=['product_type', 'status'], name='product_cor_product_1aa4c6_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'status'], name='product_cor_product_d4908f_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['barcode_internal'], name='product_cor_barcode_bb3b4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('internal_sku', ''), _negated=True), fields=('internal_sku',), name='uniq_product_variant_internal_sku_when_present'),
        ),
        migrations.AddIndex(
            model_name='productmappinghistory',
            index=models.Index(fields=['listing', 'changed_at'], name='product_cor_listing_11ac46_idx'),
        ),
        migrations.AddIndex(
            model_name='productmappinghistory',
            index=models.Index(fields=['action', 'changed_at'], name='product_cor_action_30a6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='productidentifier',
            index=models.Index(fields=['identifier_type', 'value'], name='product_cor_identif_20615f_idx'),
        ),
        migrations.AddIndex(
            model_name='productidentifier',
            index=models.Index(fields=['source'], name='product_cor_source_8f7508_idx'),
        ),
        migrations.AddConstraint(
            model_name='productidentifier',
            constraint=models.UniqueConstraint(fields=('variant', 'identifier_type', 'source', 'value'), name='uniq_product_identifier_variant_type_source_value'),
        ),
        migrations.AddConstraint(
            model_name='productidentifier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('variant', 'identifier_type', 'source'), name='uniq_primary_product_identifier_per_variant_type_source'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['marketplace', 'store', 'listing_status'], name='product_cor_marketp_1c8469_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['marketplace', 'store', 'mapping_status'], name='product_cor_marketp_095304_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['seller_article'], name='product_cor_seller__115e42_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['barcode'], name='product_cor_barcode_48160a_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['last_seen_at'], name='product_cor_last_se_3e5427_idx'),
        ),
        migrations.AddIndex(
            model_name='marketplacelisting',
            index=models.Index(fields=['last_successful_sync_at'], name='product_cor_last_su_220784_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketplacelisting',
            constraint=models.UniqueConstraint(fields=('marketplace', 'store', 'external_primary_id'), name='uniq_marketplace_listing_store_external_primary'),
        ),
        migrations.AddConstraint(
            model_name='marketplacelisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('internal_variant__isnull', False), ('mapping_status', 'matched')), models.Q(('mapping_status', 'matched'), _negated=True), _connector='OR'), name='matched_listing_requires_internal_variant'),
        ),
        migrations.AddIndex(
            model_name='promotionsnapshot',
            index=models.Index(fields=['listing', 'marketplace_promotion_id'], name='product_cor_listing_3276a5_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionsnapshot',
            index=models.Index(fields=['sync_run', 'created_at'], name='product_cor_sync_ru_591aa7_idx'),
        ),
        migrations.AddIndex(
            model_name='salesperiodsnapshot',
            index=models.Index(fields=['listing', 'period_start', 'period_end'], name='product_cor_listing_468696_idx'),
        ),
        migrations.AddIndex(
            model_name='salesperiodsnapshot',
            index=models.Index(fields=['sync_run', 'period_start'], name='product_cor_sync_ru_c966ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesperiodsnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='sales_period_snapshot_end_gte_start'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['listing', 'snapshot_at'], name='product_cor_listing_fdda8b_idx'),
        ),
        migrations.AddIndex(
            model_name='stocksnapshot',
            index=models.Index(fields=['sync_run', 'snapshot_at'], name='product_cor_sync_ru_eaa91b_idx'),
        ),
    ]
