# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_core", "0002_backfill_legacy_marketplace_products"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="marketplacesyncrun",
            constraint=models.UniqueConstraint(
                fields=("marketplace", "store", "sync_type"),
                condition=models.Q(("status__in", ["created", "running"])),
                name="uniq_active_marketplace_sync_run",
            ),
        ),
    ]
