# Generated by Django 5.2.13 on 2026-05-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_core', '0003_active_sync_run_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='import_source_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='review_state',
            field=models.CharField(choices=[('manual_confirmed', 'Manual confirmed'), ('imported_draft', 'Imported draft'), ('needs_review', 'Needs review')], default='manual_confirmed', max_length=32),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['review_state'], name='product_cor_review__f6fd0a_idx'),
        ),
    ]
