# Generated by Django 5.2.13 on 2026-04-25 13:39

import apps.operations.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('stores', '0002_businessgroup_comments_businessgroup_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('marketplace', models.CharField(choices=[('wb', 'WB'), ('ozon', 'Ozon')], max_length=16)),
                ('module', models.CharField(choices=[('discounts_excel', 'Discounts Excel')], default='discounts_excel', max_length=64)),
                ('mode', models.CharField(choices=[('excel', 'Excel'), ('api', 'API')], default='excel', max_length=16)),
                ('operation_type', models.CharField(choices=[('check', 'Check'), ('process', 'Process')], max_length=16)),
                ('status', models.CharField(max_length=64)),
                ('execution_context', models.JSONField(blank=True, default=dict)),
                ('launch_method', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('service', 'Service'), ('api', 'API')], default='manual', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('logic_version', models.CharField(max_length=128)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_basis_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_operations', to='operations.operation')),
                ('initiator_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_operations', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='stores.storeaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='check_result', to='operations.operation')),
            ],
            bases=(apps.operations.models.OperationLinkGuardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProcessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='process_result', to='operations.operation')),
                ('output_file_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_results', to='files.fileversion')),
            ],
            bases=(apps.operations.models.OperationLinkGuardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('marketplace', models.CharField(choices=[('wb', 'WB'), ('ozon', 'Ozon')], max_length=16)),
                ('module', models.CharField(choices=[('discounts_excel', 'Discounts Excel')], default='discounts_excel', max_length=64)),
                ('mode', models.CharField(choices=[('excel', 'Excel'), ('api', 'API')], default='excel', max_length=16)),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('interrupted_failed', 'Interrupted / failed')], default='created', max_length=32)),
                ('execution_context', models.JSONField(blank=True, default=dict)),
                ('launch_method', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('service', 'Service'), ('api', 'API')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_runs', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_runs', to='stores.storeaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='operation',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='operations.run'),
        ),
        migrations.CreateModel(
            name='WarningConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('warning_codes', models.JSONField(blank=True, default=list)),
                ('check_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warning_confirmations_as_check', to='operations.operation')),
                ('process_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warning_confirmations_as_process', to='operations.operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_warning_confirmations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confirmed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppliedParameterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(max_length=128)),
                ('applied_value', models.JSONField()),
                ('source', models.CharField(choices=[('store', 'Store'), ('system', 'System')], max_length=16)),
                ('parameter_version', models.CharField(blank=True, max_length=128)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameter_snapshots', to='operations.operation')),
            ],
            options={
                'ordering': ['operation_id', 'parameter_code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'parameter_code'), name='uniq_operation_parameter_snapshot')],
            },
            bases=(apps.operations.models.OperationLinkGuardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OperationDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveIntegerField()),
                ('product_ref', models.CharField(blank=True, max_length=255)),
                ('row_status', models.CharField(max_length=64)),
                ('reason_code', models.CharField(blank=True, max_length=128)),
                ('message_level', models.CharField(choices=[('info', 'Info'), ('warning_confirmable', 'Confirmable warning'), ('warning_info', 'Informational warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=32)),
                ('message', models.TextField(blank=True)),
                ('problem_field', models.CharField(blank=True, max_length=128)),
                ('final_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detail_rows', to='operations.operation')),
            ],
            options={
                'ordering': ['operation_id', 'row_no', 'id'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'row_no', 'reason_code', 'problem_field'), name='uniq_operation_detail_row_problem')],
            },
            bases=(apps.operations.models.OperationLinkGuardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OperationInputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_operation', models.CharField(max_length=64)),
                ('ordinal_no', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_input_links', to='files.fileversion')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_files', to='operations.operation')),
            ],
            options={
                'ordering': ['operation_id', 'ordinal_no', 'role_in_operation', 'id'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'role_in_operation', 'ordinal_no'), name='uniq_operation_input_role_ordinal')],
            },
            bases=(apps.operations.models.OperationLinkGuardMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OperationOutputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_kind', models.CharField(choices=[('output_workbook', 'Output workbook'), ('detail_report', 'Detail report')], default='output_workbook', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_output_links', to='files.fileversion')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='output_files', to='operations.operation')),
            ],
            options={
                'ordering': ['operation_id', 'output_kind', 'id'],
                'constraints': [models.UniqueConstraint(fields=('operation', 'output_kind'), name='uniq_operation_output_kind')],
            },
            bases=(apps.operations.models.OperationLinkGuardMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['marketplace', 'module', 'mode', 'store', 'operation_type'], name='operations__marketp_b1e5cb_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status'], name='operations__status_ad168c_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['created_at'], name='operations__created_d3385c_idx'),
        ),
    ]
