# Generated by Django 5.2.13 on 2026-04-25 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('operations', '0001_initial'),
        ('stores', '0002_businessgroup_comments_businessgroup_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed_no_errors', 'Completed without errors'), ('completed_with_warnings', 'Completed with warnings'), ('completed_with_errors', 'Completed with errors'), ('interrupted_failed', 'Interrupted / failed'), ('completed_success', 'Completed successfully'), ('completed_with_error', 'Completed with error')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type', 'check'), ('status__in', ('created', 'running', 'completed_no_errors', 'completed_with_warnings', 'completed_with_errors', 'interrupted_failed'))), models.Q(('operation_type', 'process'), ('status__in', ('created', 'running', 'completed_success', 'completed_with_warnings', 'completed_with_error', 'interrupted_failed'))), _connector='OR'), name='operation_status_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='operationoutputfile',
            constraint=models.UniqueConstraint(fields=('file_version',), name='uniq_operation_output_file_version'),
        ),
    ]
