# Generated by Django 5.2.13 on 2026-04-26 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_enforce_task005_audit_guards'),
        ('stores', '0003_connectionblock_is_stage2_1_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operation',
            name='operation_status_matches_type',
        ),
        migrations.AddField(
            model_name='operation',
            name='step_code',
            field=models.CharField(blank=True, choices=[('wb_api_prices_download', 'WB API prices download'), ('wb_api_promotions_download', 'WB API promotions download'), ('wb_api_discount_calculation', 'WB API discount calculation'), ('wb_api_discount_upload', 'WB API discount upload')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='operation',
            name='module',
            field=models.CharField(choices=[('discounts_excel', 'Discounts Excel'), ('wb_api', 'WB API')], default='discounts_excel', max_length=64),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('check', 'Check'), ('process', 'Process'), ('not_applicable', 'Not applicable')], max_length=16),
        ),
        migrations.AlterField(
            model_name='run',
            name='module',
            field=models.CharField(choices=[('discounts_excel', 'Discounts Excel'), ('wb_api', 'WB API')], default='discounts_excel', max_length=64),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['marketplace', 'mode', 'step_code'], name='operations__marketp_010087_idx'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type', 'check'), ('status__in', ('created', 'running', 'completed_no_errors', 'completed_with_warnings', 'completed_with_errors', 'interrupted_failed'))), models.Q(('operation_type', 'process'), ('status__in', ('created', 'running', 'completed_success', 'completed_with_warnings', 'completed_with_error', 'interrupted_failed'))), models.Q(('operation_type', 'not_applicable'), ('status__in', ('created', 'running', 'completed_success', 'completed_with_warnings', 'completed_with_error', 'interrupted_failed'))), _connector='OR'), name='operation_status_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('marketplace', 'wb'), ('mode', 'api'), ('operation_type', 'not_applicable'), ('step_code__in', ('wb_api_prices_download', 'wb_api_promotions_download', 'wb_api_discount_calculation', 'wb_api_discount_upload'))), models.Q(('marketplace', 'wb'), ('mode', 'api'), _negated=True), _connector='OR'), name='wb_api_operation_has_step_and_non_check_type'),
        ),
    ]
