# Generated by Django 5.2.13 on 2026-04-30 07:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_allow_multiple_operation_outputs_per_kind'),
        ('stores', '0003_connectionblock_is_stage2_1_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='module',
            field=models.CharField(choices=[('discounts_excel', 'Discounts Excel'), ('wb_api', 'WB API'), ('ozon_api', 'Ozon API')], default='discounts_excel', max_length=64),
        ),
        migrations.AlterField(
            model_name='operation',
            name='step_code',
            field=models.CharField(blank=True, choices=[('wb_api_prices_download', 'WB API prices download'), ('wb_api_promotions_download', 'WB API promotions download'), ('wb_api_discount_calculation', 'WB API discount calculation'), ('wb_api_discount_upload', 'WB API discount upload'), ('ozon_api_connection_check', 'Ozon API connection check')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='run',
            name='module',
            field=models.CharField(choices=[('discounts_excel', 'Discounts Excel'), ('wb_api', 'WB API'), ('ozon_api', 'Ozon API')], default='discounts_excel', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('marketplace', 'ozon'), ('mode', 'api'), ('operation_type', 'not_applicable'), ('step_code__in', ('ozon_api_connection_check',))), models.Q(('marketplace', 'ozon'), ('mode', 'api'), _negated=True), _connector='OR'), name='ozon_api_operation_has_step_and_non_check_type'),
        ),
    ]
