# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0005_alter_operation_module_alter_operation_step_code_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="operation",
            name="ozon_api_operation_has_step_and_non_check_type",
        ),
        migrations.AlterField(
            model_name="operation",
            name="step_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("wb_api_prices_download", "WB API prices download"),
                    ("wb_api_promotions_download", "WB API promotions download"),
                    ("wb_api_discount_calculation", "WB API discount calculation"),
                    ("wb_api_discount_upload", "WB API discount upload"),
                    ("ozon_api_connection_check", "Ozon API connection check"),
                    ("ozon_api_actions_download", "Ozon API actions download"),
                ],
                db_index=True,
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="operation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("marketplace", "ozon"),
                        ("mode", "api"),
                        ("operation_type", "not_applicable"),
                        ("step_code__in", ("ozon_api_connection_check", "ozon_api_actions_download")),
                    )
                    | models.Q(("marketplace", "ozon"), ("mode", "api"), _negated=True)
                ),
                name="ozon_api_operation_has_step_and_non_check_type",
            ),
        ),
    ]
