# Generated by Django 5.2.13 on 2026-04-30 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_remove_operation_ozon_api_operation_has_step_and_non_check_type_and_more'),
        ('stores', '0003_connectionblock_is_stage2_1_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='operation',
            name='ozon_api_operation_has_step_and_non_check_type',
        ),
        migrations.AlterField(
            model_name='operation',
            name='step_code',
            field=models.CharField(blank=True, choices=[('wb_api_prices_download', 'WB API prices download'), ('wb_api_promotions_download', 'WB API promotions download'), ('wb_api_discount_calculation', 'WB API discount calculation'), ('wb_api_discount_upload', 'WB API discount upload'), ('ozon_api_connection_check', 'Ozon API connection check'), ('ozon_api_actions_download', 'Ozon API actions download'), ('ozon_api_elastic_active_products_download', 'Ozon API Elastic active products download'), ('ozon_api_elastic_candidate_products_download', 'Ozon API Elastic candidate products download'), ('ozon_api_elastic_product_data_download', 'Ozon API Elastic product data download'), ('ozon_api_elastic_calculation', 'Ozon API Elastic calculation'), ('ozon_api_elastic_upload', 'Ozon API Elastic upload')], db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('marketplace', 'ozon'), ('mode', 'api'), ('operation_type', 'not_applicable'), ('step_code__in', ('ozon_api_connection_check', 'ozon_api_actions_download', 'ozon_api_elastic_active_products_download', 'ozon_api_elastic_candidate_products_download', 'ozon_api_elastic_product_data_download', 'ozon_api_elastic_calculation', 'ozon_api_elastic_upload'))), models.Q(('marketplace', 'ozon'), ('mode', 'api'), _negated=True), _connector='OR'), name='ozon_api_operation_has_step_and_non_check_type'),
        ),
    ]
