# Generated by Django 5.2.13 on 2026-05-02 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_remove_operation_ozon_api_operation_has_step_and_non_check_type_and_more'),
        ('product_core', '0004_productvariant_import_source_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationdetailrow',
            name='marketplace_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_detail_rows', to='product_core.marketplacelisting'),
        ),
    ]
