# Generated by Django 5.2.13 on 2026-04-25 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_enforce_task005_audit_guards'),
        ('stores', '0002_businessgroup_comments_businessgroup_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechLogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retention_until', models.DateTimeField(db_index=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('event_type', models.CharField(choices=[('excel.read_error', 'Excel read error'), ('excel.template_missing_sheet', 'Excel template missing sheet'), ('excel.template_missing_columns', 'Excel template missing columns'), ('excel.safe_write_error', 'Excel safe write error'), ('file.storage_save_error', 'File storage save error'), ('file.storage_read_error', 'File storage read error'), ('operation.execution_failed', 'Operation execution failed'), ('operation.interrupted_marked', 'Operation interrupted marked'), ('database.error', 'Database error'), ('application.exception', 'Application exception'), ('connection.future_api_error', 'Future API connection error'), ('notification.critical_created', 'Critical notification created'), ('backup.restore_check_failed', 'Backup restore check failed')], db_index=True, max_length=128)),
                ('entity_type', models.CharField(blank=True, max_length=128)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('safe_message', models.TextField(blank=True)),
                ('sensitive_details_ref', models.TextField(blank=True)),
                ('source_component', models.CharField(max_length=128)),
                ('handled_status', models.CharField(choices=[('recorded', 'Recorded'), ('notification_created', 'Notification created'), ('resolved_by_operator', 'Resolved by operator')], db_index=True, default='recorded', max_length=64)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='techlog_records', to='operations.operation')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='techlog_records', to='stores.storeaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='techlog_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='critical', max_length=16)),
                ('topic', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('archived', 'Archived')], db_index=True, default='open', max_length=32)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_notifications', to='operations.operation')),
                ('related_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_notifications', to='stores.storeaccount')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notifications', to=settings.AUTH_USER_MODEL)),
                ('related_techlog_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notification', to='techlog.techlogrecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='techlogrecord',
            index=models.Index(fields=['event_type', 'occurred_at'], name='techlog_tec_event_t_5de3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='techlogrecord',
            index=models.Index(fields=['severity', 'occurred_at'], name='techlog_tec_severit_d17270_idx'),
        ),
        migrations.AddIndex(
            model_name='techlogrecord',
            index=models.Index(fields=['store', 'occurred_at'], name='techlog_tec_store_i_d90a37_idx'),
        ),
        migrations.AddIndex(
            model_name='techlogrecord',
            index=models.Index(fields=['operation', 'occurred_at'], name='techlog_tec_operati_c54735_idx'),
        ),
        migrations.AddIndex(
            model_name='techlogrecord',
            index=models.Index(fields=['entity_type', 'entity_id'], name='techlog_tec_entity__4a0b82_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['status', 'severity', 'created_at'], name='techlog_sys_status_5d0ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='systemnotification',
            index=models.Index(fields=['related_operation', 'created_at'], name='techlog_sys_related_5aaf26_idx'),
        ),
    ]
