# Generated by Django 5.2.13 on 2026-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techlog', '0005_alter_techlogrecord_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techlogrecord',
            name='event_type',
            field=models.CharField(choices=[('excel.read_error', 'Excel read error'), ('excel.template_missing_sheet', 'Excel template missing sheet'), ('excel.template_missing_columns', 'Excel template missing columns'), ('excel.safe_write_error', 'Excel safe write error'), ('file.storage_save_error', 'File storage save error'), ('file.storage_read_error', 'File storage read error'), ('operation.execution_failed', 'Operation execution failed'), ('operation.interrupted_marked', 'Operation interrupted marked'), ('database.error', 'Database error'), ('application.exception', 'Application exception'), ('connection.future_api_error', 'Future API connection error'), ('notification.critical_created', 'Critical notification created'), ('backup.restore_check_failed', 'Backup restore check failed'), ('wb_api_auth_failed', 'WB API auth failed'), ('wb_api_rate_limited', 'WB API rate limited'), ('wb_api_timeout', 'WB API timeout'), ('wb_api_response_invalid', 'WB API response invalid'), ('wb_api_prices_download_failed', 'WB API prices download failed'), ('wb_api_promotions_download_failed', 'WB API promotions download failed'), ('wb_api_upload_failed', 'WB API upload failed'), ('wb_api_upload_status_poll_failed', 'WB API upload status poll failed'), ('wb_api_upload_partial_errors', 'WB API upload partial errors'), ('wb_api_quarantine_detected', 'WB API quarantine detected'), ('wb_api_secret_redaction_violation', 'WB API secret redaction violation'), ('ozon_api_auth_failed', 'Ozon API auth failed'), ('ozon_api_rate_limited', 'Ozon API rate limited'), ('ozon_api_timeout', 'Ozon API timeout'), ('ozon_api_response_invalid', 'Ozon API response invalid'), ('ozon_api_actions_download_failed', 'Ozon API actions download failed'), ('ozon_api_elastic_product_data_download_failed', 'Ozon API Elastic product data download failed'), ('ozon_api_secret_redaction_violation', 'Ozon API secret redaction violation')], db_index=True, max_length=128),
        ),
    ]
