# Generated by Django 5.2.13 on 2026-04-25 14:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_enforce_task005_audit_guards'),
        ('stores', '0002_businessgroup_comments_businessgroup_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('retention_until', models.DateTimeField(db_index=True)),
                ('action_code', models.CharField(choices=[('operation.check_started', 'Operation check started'), ('operation.process_started', 'Operation process started'), ('operation.warning_confirmed', 'Operation warning confirmed'), ('file.input_uploaded', 'Input file uploaded'), ('file.input_replaced', 'Input file replaced'), ('file.output_downloaded', 'Output file downloaded'), ('settings.wb_parameter_changed', 'WB parameter changed'), ('store.created', 'Store created'), ('store.changed', 'Store changed'), ('store.archived_or_deactivated', 'Store archived or deactivated'), ('store.connection_changed', 'Store connection changed'), ('store.connection_secret_changed', 'Store connection secret changed'), ('store.access_changed', 'Store access changed'), ('user.created', 'User created'), ('user.changed', 'User changed'), ('user.blocked_or_unblocked', 'User blocked/unblocked'), ('user.archived', 'User archived'), ('role.created', 'Role created'), ('role.changed', 'Role changed'), ('role.archived_or_deactivated', 'Role archived or deactivated'), ('permission.override_changed', 'Permission override changed'), ('system.dictionary_changed_by_migration', 'System dictionary changed by migration')], db_index=True, max_length=128)),
                ('entity_type', models.CharField(max_length=128)),
                ('entity_id', models.CharField(blank=True, max_length=128)),
                ('safe_message', models.TextField(blank=True)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('source_context', models.CharField(choices=[('ui', 'UI'), ('api', 'API'), ('service', 'Service'), ('automatic', 'Automatic'), ('migration', 'Migration')], default='service', max_length=32)),
                ('visible_scope', models.CharField(choices=[('limited', 'Limited'), ('full', 'Full')], default='limited', max_length=16)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='operations.operation')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='stores.storeaccount')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['action_code', 'occurred_at'], name='audit_audit_action__47956e_idx'), models.Index(fields=['store', 'occurred_at'], name='audit_audit_store_i_6735ae_idx'), models.Index(fields=['operation', 'occurred_at'], name='audit_audit_operati_d21b7d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__f5691d_idx')],
            },
        ),
    ]
