# Generated by Django 5.2.13 on 2026-04-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_ozon_actions_download_audit_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditrecord',
            name='action_code',
            field=models.CharField(choices=[('operation.check_started', 'Operation check started'), ('operation.process_started', 'Operation process started'), ('operation.warning_confirmed', 'Operation warning confirmed'), ('file.input_uploaded', 'Input file uploaded'), ('file.input_replaced', 'Input file replaced'), ('file.output_downloaded', 'Output file downloaded'), ('settings.wb_parameter_changed', 'WB parameter changed'), ('store.created', 'Store created'), ('store.changed', 'Store changed'), ('store.archived_or_deactivated', 'Store archived or deactivated'), ('store.connection_changed', 'Store connection changed'), ('store.connection_secret_changed', 'Store connection secret changed'), ('store.access_changed', 'Store access changed'), ('user.created', 'User created'), ('user.changed', 'User changed'), ('user.blocked_or_unblocked', 'User blocked/unblocked'), ('user.archived', 'User archived'), ('role.created', 'Role created'), ('role.changed', 'Role changed'), ('role.archived_or_deactivated', 'Role archived or deactivated'), ('permission.override_changed', 'Permission override changed'), ('system.dictionary_changed_by_migration', 'System dictionary changed by migration'), ('wb_api_connection_created', 'WB API connection created'), ('wb_api_connection_updated', 'WB API connection updated'), ('wb_api_connection_checked', 'WB API connection checked'), ('wb_api_prices_download_started', 'WB API prices download started'), ('wb_api_prices_download_completed', 'WB API prices download completed'), ('wb_api_prices_file_downloaded', 'WB API prices file downloaded'), ('wb_api_promotions_download_started', 'WB API promotions download started'), ('wb_api_promotions_download_completed', 'WB API promotions download completed'), ('wb_api_promotions_file_downloaded', 'WB API promotions file downloaded'), ('wb_api_discount_calculation_started', 'WB API discount calculation started'), ('wb_api_discount_calculation_completed', 'WB API discount calculation completed'), ('wb_api_discount_result_downloaded', 'WB API discount result downloaded'), ('wb_api_discount_upload_confirmed', 'WB API discount upload confirmed'), ('wb_api_discount_upload_started', 'WB API discount upload started'), ('wb_api_discount_upload_completed', 'WB API discount upload completed'), ('wb_api_discount_upload_failed', 'WB API discount upload failed'), ('ozon_api_connection_created', 'Ozon API connection created'), ('ozon_api_connection_updated', 'Ozon API connection updated'), ('ozon_api_connection_checked', 'Ozon API connection checked'), ('ozon_api_actions_download_started', 'Ozon API actions download started'), ('ozon_api_actions_download_completed', 'Ozon API actions download completed'), ('ozon_api_elastic_active_download_completed', 'Ozon API Elastic active products download completed'), ('ozon_api_elastic_candidates_download_completed', 'Ozon API Elastic candidates download completed')], db_index=True, max_length=128),
        ),
    ]
