# Generated by Django 5.2.13 on 2026-04-25 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StoreAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('marketplace', models.CharField(choices=[('wb', 'WB'), ('ozon', 'Ozon')], max_length=16)),
                ('cabinet_type', models.CharField(choices=[('store', 'Store'), ('cabinet', 'Cabinet')], default='store', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=32)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stores.businessgroup')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
