# Generated by Django 5.2.13 on 2026-04-26 09:42

from django.db import migrations, models


def migrate_connection_statuses(apps, schema_editor):
    connection_block = apps.get_model("stores", "ConnectionBlock")
    connection_block.objects.filter(status="prepared").update(status="not_configured")
    connection_block.objects.filter(status="inactive").update(status="disabled")


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_businessgroup_comments_businessgroup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionblock',
            name='is_stage2_1_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectionblock',
            name='last_check_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='connectionblock',
            name='last_check_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='connectionblock',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(migrate_connection_statuses, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='connectionblock',
            name='status',
            field=models.CharField(choices=[('not_configured', 'Not configured'), ('configured', 'Configured'), ('active', 'Active'), ('check_failed', 'Check failed'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='not_configured', max_length=32),
        ),
    ]
