# Generated by Django 5.2.13 on 2026-04-25 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0002_businessgroup_comments_businessgroup_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('kind', models.CharField(choices=[('input', 'Input'), ('output', 'Output'), ('detail_report', 'Detail report')], max_length=32)),
                ('scenario', models.CharField(choices=[('wb_discounts_excel', 'WB discounts Excel'), ('ozon_discounts_excel', 'Ozon discounts Excel')], max_length=64)),
                ('marketplace', models.CharField(choices=[('wb', 'WB'), ('ozon', 'Ozon')], max_length=16)),
                ('module', models.CharField(default='discounts_excel', max_length=64)),
                ('logical_name', models.CharField(blank=True, max_length=255)),
                ('original_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_file_objects', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='stores.storeaccount')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField()),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('storage_backend', models.CharField(default='default', max_length=64)),
                ('storage_path', models.CharField(max_length=1024)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retention_until', models.DateTimeField()),
                ('physical_status', models.CharField(choices=[('available', 'Available'), ('retention_deleted', 'Deleted by retention'), ('missing', 'Missing from storage')], default='available', max_length=32)),
                ('physical_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('operation_ref', models.CharField(blank=True, max_length=64)),
                ('run_ref', models.CharField(blank=True, max_length=64)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='files.fileobject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_file_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['file_id', '-version_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='fileobject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('marketplace', 'wb'), ('scenario', 'wb_discounts_excel')), models.Q(('marketplace', 'ozon'), ('scenario', 'ozon_discounts_excel')), _connector='OR'), name='file_object_scenario_marketplace_match'),
        ),
        migrations.AddConstraint(
            model_name='fileversion',
            constraint=models.UniqueConstraint(fields=('file', 'version_no'), name='uniq_file_version_no'),
        ),
    ]
