# Generated by Django 5.2.13 on 2026-04-26 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('stores', '0003_connectionblock_is_stage2_1_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fileobject',
            name='file_object_scenario_marketplace_match',
        ),
        migrations.AlterField(
            model_name='fileobject',
            name='scenario',
            field=models.CharField(choices=[('wb_discounts_excel', 'WB discounts Excel'), ('ozon_discounts_excel', 'Ozon discounts Excel'), ('wb_discounts_api_price_export', 'WB discounts API price export'), ('wb_discounts_api_promotion_export', 'WB discounts API promotion export'), ('wb_discounts_api_result_excel', 'WB discounts API result Excel'), ('wb_discounts_api_detail_report', 'WB discounts API detail report'), ('wb_discounts_api_upload_report', 'WB discounts API upload report')], max_length=64),
        ),
        migrations.AddConstraint(
            model_name='fileobject',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('marketplace', 'wb'), ('scenario', 'wb_discounts_excel')), models.Q(('marketplace', 'wb'), ('scenario__startswith', 'wb_discounts_api_')), models.Q(('marketplace', 'ozon'), ('scenario', 'ozon_discounts_excel')), _connector='OR'), name='file_object_scenario_marketplace_match'),
        ),
    ]
