# Generated by Django 5.2.13 on 2026-04-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_fileobject_file_object_scenario_marketplace_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileobject',
            name='scenario',
            field=models.CharField(choices=[('wb_discounts_excel', 'WB discounts Excel'), ('ozon_discounts_excel', 'Ozon discounts Excel'), ('wb_discounts_api_price_export', 'WB discounts API price export'), ('wb_discounts_api_promotion_export', 'WB discounts API promotion export'), ('wb_discounts_api_result_excel', 'WB discounts API result Excel'), ('wb_discounts_api_detail_report', 'WB discounts API detail report'), ('wb_discounts_api_upload_report', 'WB discounts API upload report'), ('ozon_api_elastic_result_report', 'Ozon API Elastic result report'), ('ozon_api_elastic_manual_upload_excel', 'Ozon API Elastic manual upload Excel')], max_length=64),
        ),
    ]
